### ISSUE TITLE
Few issues in theory manual

### ISSUE THREAD

**Issue by SaiSharathParsi1995** [idaholab/mastodon#170] opened 2018-10-15 04:03 UTC
Some hyperlinks and figure labels are mismatched in the theory manual.

1) The hyperlink "foundation-soil interface models" under sub heading Damping is not working.

2) Under sub heading "I-soil", label Figure 1 maps to Figure 3 and label Figure 2 maps to Figure 4. Figure labels in all the sections are mapped incorrectly

3) Under "seismic force", label equation 1 does't map to anything. Also the label should be eq 19.

**Comment by aeslaughter** [comment] 2018-10-15 14:02
The numbering problem is likely a known issue caused by the numbering not propagating through include files, I have a fix for this that will be ready sometime this week.

**Closed** 2018-11-15 18:41 UTC
